/**
 * Game Constants
 * Centralized configuration for all game mechanics to avoid magic numbers
 */

// Initial Game State
export const INITIAL_STATE = {
  MONEY: 10,
  SCIENCE: 0,
  FUEL: 100,
  CARGO: 0,
  SPACEPORT_CAPACITY: 2,
  ROCKET_COST: 1,
  PROFIT_PER_ROCKET: 1,
  FUEL_REFINERY_COST: 20,
  FUEL_COST_PER_ROCKET: 1,
  FUEL_PRODUCTION_PER_REFINERY: 1,
  SPACEPORT_COST: 200,
  ROCKET_EXPLOSION_CHANCE: 0.5,
};

// Cost Scaling Factors
export const COST_SCALING = {
  ROCKET_COST_EXPONENT: 1.2,
  SPACEPORT_COST_EXPONENT: 1.5,
  FUEL_REFINERY_COST_EXPONENT: 1.5,
};

// Production Values
export const PRODUCTION = {
  SCIENCE_PER_EXPLOSION: 1,
  SCIENCE_PER_SCIENCE_ROCKET: 1,
  CARGO_PER_SUCCESSFUL_LAUNCH: 0.1,
  STATION_SCIENCE_BONUS: 10,
  STATION_LOGISTICS_BONUS: 50,
  PASSIVE_CARGO_BONUS_PER_SPACEPORT: 1,
};

// Research Effects (defaults)
export const RESEARCH_EFFECTS = {
  FUEL_COST_MULTIPLIER: 0.9,
  EXPLOSION_CHANCE_MULTIPLIER: 0.95,
  PROFIT_MULTIPLIER: 1.25,
  CARGO_GENERATION_MULTIPLIER: 1.1,
  REFINERY_OUTPUT_MULTIPLIER: 1.1,
  CONSTRUCTION_COST_MULTIPLIER: 0.9,
  SPACEPORT_CAPACITY_BONUS: 3,
  CONTRACT_MONEY_MULTIPLIER: 1.2,
  STATION_LOGISTICS_MULTIPLIER: 1.25,
  STATION_SCIENCE_MULTIPLIER: 1.1,
  BUILD_ROCKET_MULTIPLIER: 1.2,
  CLEAR_EXPLOSION_MULTIPLIER: 1.2,
};

// UI Display
export const UI = {
  NOTIFICATIONS_MAX: 5,
  GRID_COLS: 3,
  TEXT_ICON_SIZE: '2xl',
  SMALL_ICON_SIZE: '4',
  OPACITY: 0.8,
};

// Time-related
export const TIME = {
  TICK_INTERVAL_MS: 1000,
  DISPLAY_TIME_THRESHOLD_SECONDS: 60,
};

// Grid layout (in SpaceportView)
export const GRID = {
  COLS: 3,
};

// Default Container Sizes
export const CONTAINERS = {
  SPACEPORT_INITIAL_COUNT: 1,
  SPACEPORT_GRID_COLUMNS: 3,
};
